### PR TITLE
External Reference Gateway Level

### LINKED ISSUE #834: Allow OpenAPI external-refs on gateway level
The following OpenAPI doesn't work when applying to Kusk: 

```yaml
openapi: 3.0.0
info:
  title: External Ref
  version: 1.0.0
paths:
  /:
    get:
      summary: Get
      operationId: get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml#/components/schemas/Pet' 
```

```sh
kusk deploy -i external-ref.yaml
❌ unable to load spec: encountered disallowed external reference: "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml#/components/schemas/Pet"
```

### PR DESCRIPTION
**Pull request by kylehodgetts**
This PR closed #834

### CODE REVIEW

File: cmd/kusk/cmd/deploy.go [hunk 1]
```diff
@@ -104,31 +103,36 @@ var deployCmd = &cobra.Command{
...
-					return err
-				}
-				api.SetResourceVersion(ap.GetResourceVersion())
-				if err := k8sclient.Update(ctx, api, &client.UpdateOptions{}); err != nil {
-					reportError(err)
-					return err
-				}
-				kuskui.PrintSuccess(fmt.Sprintf("api.gateway.kusk.io/%s updated", api.Name))
-			} else {
+			if !apierrors.IsAlreadyExists(err) {
```
Comment (jasmingacic) [inline cmd/kusk/cmd/deploy.go:120]: Can we make this AlreadyExists :D

**Review by jasmingacic — APPROVED** [review]
But otherwise it is looking good

there is one mini comment which you can ignore if you want to
